{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "ReEduc.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "authorship_tag": "ABX9TyNZYMScluo03+NEksPcWNhs",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/shtsousa/projects/blob/main/ReEduc.py\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "5kSZnaiHOW-y",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "d1bb6a99-c518-432b-aa35-7bc6d2d7e0d4"
      },
      "source": [
        "#Abertura do programa\n",
        "print(\"Seja bem-vindo ao Programa de Re-educacao alimentar\\nLembramos que todos os dados aqui são baseados numa amostra não comprovada podendo varias em seus indices\")\n",
        "nome=input(\"Insira seu nome: \")\n",
        "\n",
        "print(f\"\\nOla {nome}, seja bem vindo ao Programa de Re-educacao alimentar ltda\\n\")\n",
        "\n",
        "#Cadastro do cliente e importação de algumas bibliotecas\n",
        "import os\n",
        "import re\n",
        "import pandas\n",
        "print(\"Para melhor atendermos, vamos realizar seu cadastro\")\n",
        "import getpass #getpass pra senha\n",
        "log = input(\"Login: \")\n",
        "senha = getpass.getpass(prompt='Senha: ', stream=None)\n",
        "email = input(\"E-mail: \")\n",
        "print(\"Cadastro realizado com sucesso !\")\n",
        "\n",
        "#Inserção de dados para calcular\n",
        "print(\"Agora que nos conhecemos melhor, nos diga um pouco sobre você\")\n",
        " \n",
        "alt = float(input(\"Qual sua altura(M): \"))\n",
        "idade = int(input(\"Qual sua idade: \"))\n",
        "peso = float(input(\"Qual seu peso(Kg): \"))\n",
        "sexo = str(input(\"Digita o seu sexo (M/F): \"))\n",
        "imc = peso / (alt ** 2)\n",
        "\n",
        "\n",
        "if sexo == \"M\":\n",
        "    if idade == 1:\n",
        "        if imc >= 19.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 18.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 14.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 2:\n",
        "        if imc >= 18.7:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 17.4:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 14:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 3:\n",
        "        if imc >= 18.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 17:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.4:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 4:\n",
        "        if imc >= 18:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 16.7:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 5:\n",
        "        if imc >= 18.1:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 16.7:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 6:\n",
        "        if imc >= 18.4:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 16.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 7:\n",
        "        if imc >= 18.7:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 17.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.3:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if id == 8:\n",
        "        if imc >= 19.4:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 17.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 9:\n",
        "        if imc >= 20.1:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 18:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 10:\n",
        "        if imc >= 28.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 25:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 17.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 11:\n",
        "        if imc >= 22:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 19.3:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 14.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 12:\n",
        "        if imc >= 23:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 20:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 14.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 13:\n",
        "        if imc >= 24.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 21:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 15:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 14:\n",
        "        if imc >= 25.3:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 21.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 15.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 15:\n",
        "        if imc >= 26.4:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 22.8:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 16.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 16:\n",
        "        if imc >= 27.3:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 23.7:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 16.7:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 17:\n",
        "        if imc >= 28:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 24.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 17.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 18:\n",
        "        if imc >= 28.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 25:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 17.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade >= 19:\n",
        "        if imc >= 30:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 25:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 18.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "if sexo == \"F\":\n",
        "    if idade == 1:\n",
        "        if imc >= 19.4:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 17.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 2:\n",
        "        if imc >= 18.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 17.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 3:\n",
        "        if imc >= 18.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 16.8:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 4:\n",
        "        if imc >= 18.3:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 16.8:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 5:\n",
        "        if imc >= 18.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 17:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 12.8:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 6:\n",
        "        if imc >= 18.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 17.1:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 12.8:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 7:\n",
        "        if imc >= 19.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 17.4:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 12.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 8:\n",
        "        if imc >= 20.1:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 17.8:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 9:\n",
        "        if imc >= 21:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 18.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.3:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 10:\n",
        "        if imc >= 22:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 19.1:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 13.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 11:\n",
        "        if imc >= 23.2:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 20:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 14:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 12:\n",
        "        if imc >= 24.4:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 20.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 14.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 13:\n",
        "        if imc >= 25.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 22:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 15.1:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 14:\n",
        "        if imc >= 26.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 22.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 15.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 15:\n",
        "        if imc >= 27.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 23.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 16.1:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 16:\n",
        "        if imc >= 28.3:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 24.3:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 16.4:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 17:\n",
        "        if imc >= 28.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 24.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 16.6:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade == 18:\n",
        "        if imc >= 28.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 24.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 16.7:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))\n",
        "\n",
        "    if idade >= 19:\n",
        "        if imc >= 30:\n",
        "            print(\"O seu IMC é {:.2f} e você tem obsidade I\".format(imc))\n",
        "        elif imc >= 24.9:\n",
        "            print(\"O seu IMC é {:.2f} e você tem pré obsidade\".format(imc))\n",
        "        elif imc >= 18.5:\n",
        "            print(\"O seu IMC é {:.2f} e você tem peso normal\".format(imc))\n",
        "        else:\n",
        "            print(\"O seu IMC é {:.2f} e você tem magreza\".format(imc))"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Seja bem-vindo ao Programa de Re-educacao alimentar\n",
            "Lembramos que todos os dados aqui são baseados numa amostra não comprovada podendo varias em seus indices\n",
            "Insira seu nome: Nayara Torres\n",
            "\n",
            "Ola Nayara Torres, seja bem vindo ao Programa de Re-educacao alimentar ltda\n",
            "\n",
            "Para melhor atendermos, vamos realizar seu cadastro\n",
            "Login: Nay23\n",
            "Senha: ··········\n",
            "E-mail: nayaracristina04@outlook.com\n",
            "Cadastro realizado com sucesso !\n",
            "Agora que nos conhecemos melhor, nos diga um pouco sobre você\n",
            "Qual sua altura(M): 1.63\n",
            "Qual sua idade: 23\n",
            "Qual seu peso(Kg): 60\n",
            "Digita o seu sexo (M/F): F\n",
            "O seu IMC é 22.58 e você tem peso normal\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "hp3mMlZtNcm0"
      },
      "source": [
        ""
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}